## Set environment variables
env:
  TERM: alacritty
  WINIT_X11_SCALE_FACTOR: '1.0'

## Terminal window settings
window:
  dimensions:
    columns: 82
    lines: 24

  padding:
    x: 10
    y: 10

  decorations: full
  startup_mode: Windowed
  dynamic_title: true

  ## scrolling
  history: 10000
  multiplier: 3

  ## Background opacity
  opacity: 1.0

## Cursor
cursor:
  style:
    shape: Block
    blinking: On

  unfocused_hollow: false

## Live config reload
live_config_reload: true

## Shell
#shell:
#  program: /bin/zsh
#  args:
#    - --login
font:
  # Normal (roman) font face
  normal:
    family: JetBrainsMono Nerd Font
    #style: Regular

  # Bold font face
  bold:
    family: JetBrainsMono Nerd Font
    #style: Bold

  # Italic font face
  italic:
    family: JetBrainsMono Nerd Font
    #style: Italic

  # Bold italic font face
  bold_italic:
    family: JetBrainsMono Nerd Font
    #style: Bold Italic

  # Point size
  size: 10
  # Offset
  #offset:
  #  x: 0
  #  y: 0
  # Glyph offset
  #glyph_offset:
  #  x: 0
  #  y: 0
colors:
  # Default colors
  primary:
    background: '0x0d1117'
    foreground: '0xb3b1ad'

  # Normal colors
  normal:
    black: '0x484f58'
    red: '0xff7b72'
    green: '0x3fb950'
    yellow: '0xd29922'
    blue: '0x58a6ff'
    magenta: '0xbc8cff'
    cyan: '0x39c5cf'
    white: '0xb3b1ad'

  # Bright colors
  bright:
    black: '0x6e7681'
    red: '0xffa198'
    green: '0x56d364'
    yellow: '0xe3b341'
    blue: '0x79c0ff'
    magenta: '0xd2a8ff'
    cyan: '0x39c5cf'
    white: '0xb3b1ad'

  indexed_colors:
    - { index: 16, color: '0xd18616' }
    - { index: 17, color: '0xffa198' }
theme: github_dark_default
